### ISSUE TITLE
python crashes on startup

### ISSUE THREAD

**Issue by under-score** [tugbaca/Copy-Move-Forgery-Detection#1]
Tried to install all modules and adjusted the path to something existing in #161 and #175 of
`root.filename = filedialog.asksaveasfilename(initialdir="~/PycharmProjects/Bitirme/Test-Images"`
but python keeps crashing when clicking on the open action

![Bildschirmfoto 2021-11-25 um 09 46 31](https://user-images.githubusercontent.com/2796454/143410645-003f4e88-5fd1-4f92-bdbb-c9dd77c6cfae.jpg)

Any idea?

**Comment by cantugba** [comment]
You should determine the file path of the images to be used for the test according to your operating system and the location of the files. It gives an error because it cannot find the folder named "Bitirme". File path; I updated it to 167(for open image) - 171(for save image) : initialdir="~/PycharmProjects". Thanks for your comment

**Comment by under-score** [comment]
already did this (would even recommend to change a dir that is always there like "~") but this was not the reason for the exception.

**Comment by cantugba** [comment]
I checked after editing the file path and there doesn't seem to be any problem. If you are still getting errors, I suggest you check your package versions. if u want  we can look at the details of the error together. You can contact with me my email address. Mail: tugbacan57@outlook.com
